"""
src/agents/compiler.py
======================
Final Report Compiler Agent
----------------------------
Last node in the LangGraph graph. Only executes AFTER the analyst has
approved the draft report via the HITL node.

Responsibilities:
  1. Apply any analyst override notes to the approved draft
  2. Add compliance header / disclaimer footer
  3. Stamp the report with metadata (session_id, tickers, timestamp)
  4. Store final_report in state and mark workflow COMPLETE

Node signature (LangGraph):
    def compiler_node(state: AgentState) -> dict
"""

from __future__ import annotations

import time
from datetime import datetime, timezone

from loguru import logger

from src.observability import trace_node
from src.state import AgentState, WorkflowStatus

# ---------------------------------------------------------------------------
# Disclaimer template (required by financial compliance rails)
# ---------------------------------------------------------------------------

COMPLIANCE_DISCLAIMER = """
---
> **⚠ Compliance Disclaimer**
> This report is generated by an AI research assistant and is intended for
> informational purposes only. It does **not** constitute investment advice,
> a solicitation to buy or sell any security, or a recommendation of any kind.
> All data is sourced from publicly available documents. Past performance is
> not indicative of future results. Consult a qualified financial advisor
> before making any investment decisions.
>
> *Generated by: Multi-Agent RAG Financial Analyst System*
> *Classification: INTERNAL RESEARCH USE ONLY*
""".strip()


@trace_node("compiler")
def compiler_node(state: AgentState) -> dict:
    """
    LangGraph node: finalise and stamp the approved draft report.

    Reads from state:
        draft_report, hitl_approved, override_notes, session_id,
        ticker, report_version, node_timings

    Writes to state:
        final_report, report_version, status, node_timings
    """
    t0         = time.perf_counter()
    session_id = state.get("session_id", "unknown")
    version    = state.get("report_version", 1)

    logger.info(f"[compiler] START | session={session_id} | version={version}")

    draft         = state.get("draft_report", "")
    override_notes = state.get("override_notes", "").strip()
    tickers       = state.get("ticker", [])
    timestamp     = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # --- Report header ---
    header_lines = [
        f"# Financial Research Report",
        f"",
        f"| Field         | Value |",
        f"|---------------|-------|",
        f"| **Tickers**   | {', '.join(tickers) if tickers else 'Multiple'} |",
        f"| **Generated** | {timestamp} |",
        f"| **Session**   | `{session_id}` |",
        f"| **Version**   | v{version} |",
        f"| **Status**    | ✅ Analyst Approved |",
        f"",
    ]

    # Append analyst override note as a callout block if present
    if override_notes:
        header_lines += [
            f"> **📝 Analyst Notes (Override Applied)**",
            f"> {override_notes}",
            f"",
        ]

    header = "\n".join(header_lines)

    # Assemble: header + draft body + disclaimer
    final_report = f"{header}\n{draft}\n\n{COMPLIANCE_DISCLAIMER}"

    elapsed = time.perf_counter() - t0
    logger.success(
        f"[compiler] DONE | final_report_len={len(final_report)} chars | {elapsed:.2f}s"
    )

    return {
        "final_report":  final_report,
        "report_version": version,
        "status":        WorkflowStatus.COMPLETE,
        "node_timings":  {**state.get("node_timings", {}), "compiler": round(elapsed, 3)},
    }